Car/urls.py
from django.urls import path
from .views import *

app_name = 'Car'
urlpatterns = [
    path('', home, name="home"),
    path('contact', contactus, name="contact"),
    path('qt', quotev, name="qt"),
    path('blogs', blog, name="blog"),
    path('gallery', galleryv, name="gallery"),
    path('about', spabout, name='about'),
    path('services', service, name='service'),
    path('stuffs', stuff, name='stuff'),
    path('blog/<int:id>/', post_detail, name='post_detail')


]

carremoval/urls.py
from django.contrib import admin
from django.urls import path, include
from Car.views import *
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',home)
    path('', include('Car.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Car/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.utils.timezone import datetime
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.


class Slider(models.Model):
    title = models.CharField(max_length=100)
    photo = models.ImageField(
        upload_to='media/slider', height_field=None, width_field=None)
    message = models.CharField(max_length=200, default='')
    alt = models.CharField(max_length=30)

    def __str__(self):
        return self.title


class Address(models.Model):
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.location


class About_footer(models.Model):
    name = models.CharField(max_length=200)
    desciption = models.TextField(
        max_length=280, help_text='maximum size is 280 character')
    logo = models.ImageField(upload_to='media/logo')
    pub_date = models.DateField(default=datetime.now)

    def __str__(self):
        return self.name


class SocialMedia(models.Model):
    facebook = models.CharField(max_length=600, null=True, blank=True)
    x = models.CharField(max_length=600, null=True, blank=True)
    linkedin = models.CharField(max_length=600, null=True, blank=True)
    googleplus = models.CharField(max_length=600, null=True, blank=True)
    instagram = models.CharField(max_length=600, null=True, blank=True)

    def __str__(self):
        return "all social media"


WEEKDAYS = [
    (1, _("Monday")),
    (2, _("Tuesday")),
    (3, _("Wednesday")),
    (4, _("Thursday")),
    (5, _("Friday")),
    (6, _("Saturday")),
    (7, _("Sunday")),


]

STATUS = [
    ('OFF', 'OFF'),
    ('ON', 'ON')
]


class OpeningHours(models.Model):

    weekday = models.IntegerField(null=True, blank=True, choices=WEEKDAYS)
    from_hour = models.TimeField(null=True, blank=True)
    to_hour = models.TimeField(null=True, blank=True)
    status = models.CharField(max_length=30, default='OFF', choices=STATUS)

    class Meta:
        ordering = ('weekday', 'from_hour')
        unique_together = ('weekday', 'from_hour', 'to_hour')

    def __unicode__(self):
        return u'%s: %s - %s' % (self.get_weekday_display(),
                                 self.from_hour, self.to_hour)

    def __str__(self):
        return self.get_weekday_display()


class Gallery(models.Model):
    photo_name = models.CharField(max_length=50)
    photo = models.ImageField(
        upload_to='media/Gallery', height_field=None, width_field=None, help_text='photo width =1200px height = 800')
    publish = models.DateTimeField(default=timezone.now)
    alt = models.CharField(max_length=30)

    def __str__(self):
        return self.photo_name

    class Meta:
        ordering = ('-publish',)


class Contactus(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=250)
    phone = models.CharField(max_length=14)
    address = models.CharField(max_length=250)
    message = models.CharField(max_length=900)
    recieve_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    make = models.CharField(max_length=60)
    model = models.CharField(max_length=100)
    year = models.CharField(max_length=4)
    suburb = models.CharField(max_length=300)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=14)
    email = models.EmailField()
    re_date = models.DateField(auto_now_add=True)
    message = models.TextField(max_length=900)

    def __str__(self):
        return self.name + self.suburb


class All_HeadDes(models.Model):
    gallery_mes = models.CharField(max_length=170)
    slider_mes = models.CharField(max_length=170)
    service_mes = models.CharField(max_length=170)
    blog_mes = models.CharField(max_length=170)
    stuff_mes = models.CharField(max_length=170)


class Stuff(models.Model):
    name = models.CharField(max_length=50)
    photo = photo = models.ImageField(
        upload_to='media/stuff', height_field=None, width_field=None)
    job_position = models.CharField(max_length=100)
    facebook = models.URLField(max_length=200)
    x = models.URLField(max_length=200)
    gplus = models.URLField(max_length=200)
    instagram = models.URLField(max_length=200)


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    photo = models.ImageField(
        upload_to='media/post', help_text='Image size should be width= 470x height=570')
    alt = models.CharField(max_length=30, null=True, blank=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class About(models.Model):
    title = models.CharField(max_length=40, default='ozzy auto recycle')
    aboutus = models.TextField(
        max_length=600, help_text='maximum character is 600')
    photo = models.ImageField(
        upload_to='media/about', help_text='Image size should be width= 800px height=650px')
    alt = models.CharField(max_length=20)
    slogan = models.TextField(
        max_length=150, help_text='max length is 150 character')

    def __str__(self):
        return self.title


class Servicetype(models.Model):
    services = models.CharField(max_length=50)

    def __str__(self):
        return self.services


class Service(models.Model):
    title = models.CharField(max_length=50)
    photo = photo = models.ImageField(
        upload_to='media/about', help_text='Image size should be width= 800px height=480px')
    description = models.TextField(max_length=700)
    service_type = models.ForeignKey(
        Servicetype, on_delete=models.CASCADE, related_name='service_type')
    alt = models.CharField(
        max_length=40, help_text='please meaning full name for photo', null=True, blank=True)

    def __str__(self):
        return self.title


class AllMeta(models.Model):
    about_meta_title = models.CharField(
        max_length=60, null=True, blank=True, help_text='meta title should be 50-60 character')
    about_meta_keyword = models.CharField(
        max_length=220, null=True, blank=True, help_text='meta keyword should be 10-20 meta keyword')
    about_meta_desc = models.CharField(max_length=160, null=True, blank=True,
                                       help_text='meta description should be 155-160 character')
    blog_meta_title = models.CharField(
        max_length=60, null=True, blank=True, help_text='meta title should be 50-60 character')
    blog_meta_keyword = models.CharField(
        max_length=220, null=True, blank=True, help_text='meta keyword should be 10-20 meta keyword')
    blog_meta_desc = models.CharField(
        max_length=160, null=True, blank=True, help_text='meta description should be 155-160 character')

    contact_meta_title = models.CharField(
        max_length=60, null=True, blank=True, help_text='meta title should be 50-60 character')
    contact_meta_keyword = models.CharField(
        max_length=220, null=True, blank=True, help_text='meta keyword should be 10-20 meta keyword')
    contact_meta_desc = models.CharField(
        max_length=160, null=True, blank=True, help_text='meta description should be 155-160 character')

    gallery_meta_title = models.CharField(
        max_length=60, null=True, blank=True, help_text='meta title should be 50-60 character')
    gallery_meta_keyword = models.CharField(
        max_length=220, null=True, blank=True, help_text='meta keyword should be 10-20 meta keyword')
    gallery_meta_desc = models.CharField(
        max_length=160, null=True, blank=True, help_text='meta description should be 155-160 character')

    quote_meta_title = models.CharField(
        max_length=60, null=True, blank=True, help_text='meta title should be 50-60 character')
    quote_meta_keyword = models.CharField(
        max_length=220, null=True, blank=True, help_text='meta keyword should be 10-20 meta keyword')
    quote_meta_desc = models.CharField(
        max_length=160, null=True, blank=True, help_text='meta description should be 155-160 character')

    index_meta_title = models.CharField(
        max_length=60, null=True, blank=True, help_text='meta title should be 50-60 character')
    index_meta_keyword = models.CharField(
        max_length=220, null=True, blank=True, help_text='meta keyword should be 10-20 meta keyword')
    index_meta_desc = models.CharField(
        max_length=160, null=True, blank=True, help_text='meta description should be 155-160 character')

    service_meta_title = models.CharField(
        max_length=60, null=True, blank=True, help_text='meta title should be 50-60 character')
    service_meta_keyword = models.CharField(
        max_length=220, null=True, blank=True, help_text='meta keyword should be 10-20 meta keyword')
    service_meta_desc = models.CharField(
        max_length=160, null=True, blank=True, help_text='meta description should be 155-160 character')

    def __str__(self):
        return "all_meta"

Car/views.py
from django.shortcuts import render, HttpResponse
from .models import *
from django.contrib import messages

# Create your views here.


def home(request):
    slider = Slider.objects.all()
    gall_photo = Gallery.objects.all()
    return render(request, 'Car/index.html', {'photos': gall_photo, 'slider': slider})


def contactus(request):
    if request.method == "POST":
        contactus = Contactus()
        name = request.POST.get("name")
        email = request.POST.get("email")
        phone = request.POST.get("tel")
        address = request.POST.get("address")
        message = request.POST.get("message")

        contactus.name = name
        contactus.email = email
        contactus.phone = phone
        contactus.address = address
        contactus.message = message
        # contactus.recieve_date = date1
        try:
            contactus.save()
            messages.success(request, "Data inserted successfully")
        except:
            messages.warning(request, "Data was not inserted")
    return render(request, 'Car/contact.html')


def quotev(request):
    if request.method == 'POST':
        quote = Quote()
        make = request.POST.get("make")
        model = request.POST.get("model")
        year = request.POST.get("year")
        suburb = request.POST.get("suburb")
        name = request.POST.get("name")
        phone = request.POST.get("tel")
        email = request.POST.get("email")
        message = request.POST.get("message")
        quote.make = make
        quote.model = model
        quote.year = year
        quote.suburb = suburb
        quote.name = name
        quote.phone = phone
        quote.email = email
        quote.message = message
        quote.save()
        return HttpResponse("<h1> your submission was successful </h1>,<br> <h1> <a href='qt'>Back</a></h1>")
    return render(request, 'Car/getquote.html')


def blog(request):
    all_post = Post.objects.filter(status='published')
    all_post = all_post[0:9]

    return render(request, 'Car/blog.html', {'posts': all_post})


def galleryv(request):
    gallery = Gallery.objects.all()[0:30]
    return render(request, 'Car/gallery.html', {'gallery': gallery})


def spabout(request):
    return render(request, 'Car/about.html')


def service(request):
    return render(request, 'Car/service.html')


def stuff(request):
    all_stuff = Stuff.objects.all()
    return render(request, 'Car/stuff.html', {'stuffs': all_stuff})


def post_detail(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'Car/blog-details.html', {'post': post})

Car/templates/Car/_footer.html
<!-- Start Contact info -->

<div class="contact-imfo-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fa fa-volume-control-phone"></i>
                <div class="overflow-hidden">
                    <h4>Phone</h4>
                    <p class="lead">
                        <a href="tel:">{{ address_info.phone}}</a>
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-envelope"></i>
                <div class="overflow-hidden">
                    <h4>Email</h4>
                    <p class="lead">
                        {{address_info.email}}
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-map-marker"></i>
                <div class="overflow-hidden">
                    <h4>Location</h4>
                    <p class="lead">
                        {{address_info.location}}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Contact info -->
<!-- Start Footer -->
<footer class="footer-area bg-f">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <h3>{{footer_info.name}} </h3>
                <p>{{footer_info.desciption}}</p>

            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Opening hours</h3>


                {%for hour in on%}
                <p><span class="text-color">{{hour.get_weekday_display}}: </span>{{hour.from_hour}}: {{hour.to_hour}}
                </p>
                {%endfor%}

                {%for hour in off%}
                <p><span class="text-color">{{hour.get_weekday_display}}: </span>{{hour.status}}
                </p>
                {%endfor%}

                <!-- <p><span class="text-color">Tue-Wed :</span> 9:Am - 10PM</p>
                <p><span class="text-color">Thu-Fri :</span> 9:Am - 10PM</p>
                <p><span class="text-color">Sat-Sun :</span> 5:PM - 10PM</p> -->


            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Contact info</h3>
                <p class="lead">{{address_info.location}}</p>
                <p class="lead"><a href="#">{{address_info.phone}}</a></p>
                <p><a href="#"> {{address_info.email}}</a></p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Subscribe</h3>
                <div class="subscribe_form">
                    <form class="subscribe_form">
                        <input name="EMAIL" id="subs-email" class="form_input" placeholder="Enter Email Address..."
                            type="email">
                        <button type="submit" class="submit">SUBSCRIBE</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
                <ul class="list-inline f-social">
                    <li class="list-inline-item"><a href="{{social_media.facebook}}" target='_blank'><i
                                class="fa fa-facebook" aria-hidden="true"></i></a>

                    </li>

                    <li class="list-inline-item"><a href="{{social_media.x}}" target="_blank"><i class="fa fa-twitter"
                                aria-hidden="true"></i></a>
                    </li>
                    <li class="list-inline-item"><a href="{{social_media.linkedin}}" target="_blank"><i
                                class="fa fa-linkedin" aria-hidden="true"></i></a>
                    </li>
                    <li class="list-inline-item"><a href="{{social_media.googleplus}}" target="_blank"><i
                                class="fa fa-google-plus" aria-hidden="true"></i></a>
                    </li>
                    <li class="list-inline-item"><a href="{{social_media.instagram}}" target="_blank"><i
                                class="fa fa-instagram" aria-hidden="true"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="company-name">All Rights Reserved. &copy;{% now "Y" %} <a href="#">Ozzy auto recycle</a>
                        Design By :
                        <a href="#">nazari</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

</footer>
<!-- End Footer -->

Car/templates/Car/_header.html
{%load static%}
<!DOCTYPE html>
<h<html lang="en"><!-- Basic -->

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <!-- Mobile Metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Site Metas -->



        <!-- Site Icons -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
        <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
        <!-- Site CSS -->
        <link rel="stylesheet" href="{% static 'css/style.css'%}">

        <!-- Responsive CSS -->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <!-- contact us css -->
        <link rel="stylesheet" href="{% static 'css/custom.css'%}">
        <!-- Custom CSS -->
        <!-- <link rel="stylesheet" href="{% static 'css/custom.css'% }"> -->

        <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    </head>

    <body>
        <!-- Start header -->
        <header class="top-navbar">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container">
                    <a class="navbar-brand" href="/">
                        <img src="{{footer_info.logo.url}}" alt="logo" />
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food"
                        aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbars-rs-food">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item active"><a class="nav-link" href="{%url 'Car:home'%}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{%url 'Car:qt'%}">Get Quote</a></li>
                            <li class="nav-item"><a class="nav-link" href="{%url 'Car:service'%}">services</a></li>
                            <li class="nav-item"><a class="nav-link" href="{%url 'Car:gallery'%}">Gallery</a></li>
                            <li class="nav-item"><a class="nav-link" href="{%url 'Car:blog'%}">Blog</a></li>
                            <li class="nav-item"><a class="nav-link" href="{%url 'Car:about'%}">About</a></li>
                            <li class="nav-item"><a class="nav-link" href="{%url 'Car:stuff'%}">Stuff</a></li>


                            <li class="nav-item"><a class="nav-link" href="{%url 'Car:contact'%}">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <!-- End header -->

Car/templates/Car/about.html
{%extends 'base.html'%}
{%load static%}
{% block metadescription %}

<title>{{all_meta.about_meta_title}}</title>
<meta name="keywords" content="{{all_meta.about_meta_keyword}}">
<meta name="description" content="{{all_meta.about_meta_desc}}">

{% endblock %}
{%block content%}
<!-- Start header -->
<div class="all-page-title page-breadcrumb">
	<div class="container text-center">
		<div class="row">
			<div class="col-lg-12">
				<h1>About Us</h1>
			</div>
		</div>
	</div>
</div>
<!-- End header -->

<!-- Start About -->
<div class="about-section-box">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-6">
				<img src="{{about.photo.url}}" alt="{{about.alt}}" class="img-fluid">
			</div>
			<div class="col-lg-6 col-md-6 text-center">
				<div class="inner-column">
					<h1>Welcome To <span> {{about.title}}</span></h1>
					<h4>Little Story</h4>
					<p> {{about.aboutus}}</p>

					<a class="btn btn-lg btn-circle btn-outline-new-white" href="qt">get instance quote</a>
				</div>
			</div>

		</div>
	</div>
</div>
<!-- End About -->

<!-- Start Menu -->
<div class="menu-box">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="heading-title text-center">
					<h2>services</h2>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
				</div>
			</div>
		</div>


		<style>
			/* CSS styles specific to this page */


			.container1 {
				max-width: auto px;
				margin: 0 auto;
				padding: 20px;
				background-color: #fff;
				border-radius: 8px;
				box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
			}

			h1,
			h2 {
				color: #333;
			}

			.service {
				margin-bottom: 30px;
				padding: 20px;
				background-color: #f9f9f9;
				border-radius: 8px;
				box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
				overflow: hidden;
			}

			.service img {
				width: 100%;
				border-radius: 8px;
				margin-bottom: 10px;
			}

			/* Add more styles as needed */
		</style>
		<div class="container1">
			<h1>Our Services</h1>
			{%for item in service%}
			<div class="service">
				<img src="{{item.photo.url}}" alt="{{item.alt}}">
				<h2>{{item.title}}</h2>
				<p>{{item.description}}</p>
				<!-- Add more details about Service 1 -->
			</div>
			{%endfor%}


			<!-- Add more services as needed -->

		</div>






	</div>
</div>
</div>
<!-- End Menu -->
{%endblock%}

Car/templates/Car/blog-details.html
{%extends 'base.html'%}
{%load static%}
{% block metadescription %}

<title>{{all_meta.blog_meta_title}}</title>
<meta name="keywords" content="{{all_meta.blog_meta_keyword}}">
<meta name="description" content="{{all_meta.blog_meta_desc}}">


{% endblock %}
{%block content%}

<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
	<div class="container text-center">
		<div class="row">
			<div class="col-lg-12">
				<h1>Blog</h1>
			</div>
		</div>
	</div>
</div>
<!-- End All Pages -->

<!-- Start blog details -->
<div class="blog-box">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="heading-title text-center">
					<h2>{{post.title}}</h2>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xl-8 col-lg-8 col-12">
				<div class="blog-inner-details-page">
					<div class="blog-inner-box">
						<div class="side-blog-img">
							<img class="img-fluid" src="{{post.photo.url}}" alt="{{post.alt}}">
							<div class="date-blog-up">
								27 Fab
							</div>
						</div>
						<div class="inner-blog-detail details-page">
							<h3>{{post.title}}</h3>
							<ul>
								<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{post.author}}</span></li>
								<li>|</li>
								<li><i class="zmdi zmdi-time"></i>Date : <span>{{post.publish}}</span></li>
							</ul>

							<p> {{post.body}}</p>


						</div>
					</div>


				</div>
			</div>

		</div>
	</div>
</div>
<!-- End details -->

{%endblock%}

Car/templates/Car/blog.html
{%extends 'base.html'%}
{%load static%}
{% block metadescription %}

<title>{{all_meta.blog_meta_title}}</title>
<meta name="keywords" content="{{all_meta.blog_meta_keyword}}">
<meta name="description" content="{{all_meta.blog_meta_desc}}">


{% endblock %}
{%block content%}

<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
	<div class="container text-center">
		<div class="row">
			<div class="col-lg-12">
				<h1>Blog</h1>
			</div>
		</div>
	</div>
</div>
<!-- End All Pages -->

<!-- Start blog -->
<div class="blog-box">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="heading-title text-center">
					<h2>Blog</h2>
					<p>{{allmessage.blog_mes}}</p>
				</div>
			</div>
		</div>

		<div class="row">


			{%for item in posts%}
			<div class="col-lg-4 col-md-6 col-12">
				<div class="blog-box-inner">
					<div class="blog-img-box">
						<img class="img-fluid" src="{{item.photo.url}}" alt="{{item.alt}}">
					</div>
					<div class="blog-detail">
						<h4>{{item.title}}</h4>
						<ul>
							<li><span>{{item.author}}</span></li>
							<li>|</li>
							<li><span>{{item.publish}}</span></li>
						</ul>
						<p>{{item.body|truncatechars:350}} </p>

						<a class="btn btn-lg btn-circle btn-outline-new-white"
							href="{%url 'Car:post_detail' item.id%}">Read More</a>
					</div>
				</div>

			</div>
			{%endfor%}

		</div>

	</div>
</div>
<!-- End blog -->
<br><br><br><br>
{%endblock%}

Car/templates/Car/contact.html
{%extends 'base.html' %}
{%load static%}
{% block metadescription %}

<title>{{all_meta.contact_meta_title}}</title>
<meta name="keywords" content="{{all_meta.contact_meta_keyword}}">
<meta name="description" content="{{all_meta.contact_meta_desc}}">


{% endblock %}
{%block content%} <!-- Start All Pages -->
<style>
	.containerc {
		width: 70%;
		margin-top: 30px;
		margin-bottom: 10px;
		margin-left: 15%;

		padding: 20px;
		border: 1px solid #ccc;
		border-radius: 5px;
	}

	label {
		display: block;
		margin-bottom: 5px;
	}

	input[type="text"],
	input[type="email"],
	textarea {
		width: 100%;
		padding: 10px;
		margin-bottom: 10px;
		border: 1px solid #ccc;
		border-radius: 5px;
		resize: vertical;
	}

	input[type="submit"] {
		background-color: #4CAF50;
		color: white;
		padding: 10px 20px;
		border: none;
		border-radius: 5px;
		cursor: pointer;
	}

	input[type="submit"]:hover {
		background-color: #45a049;
	}
</style>
<div class="all-page-title page-breadcrumb">
	<div class="container text-center">
		<div class="row">
			<div class="col-lg-12">
				<h1>Contact us</h1>
			</div>
		</div>
	</div>
</div>
<!-- End All Pages -->

<!-- Start Contact -->


<div class="containerc">

	<form method="post">
		{%csrf_token%}
		<label for="name">Name:</label>
		<input type="text" id="name" name="name" required>

		<label for="email">Email:</label>
		<input type="email" id="email" name="email" required>

		<label for="phone">Phone:</label>
		<input type="tel" id="date" name="tel">

		<label for="address">Address:</label>
		<input type="text" id="address" name="address" required>



		<label for="message">Message:</label>
		<textarea id="message" name="message" rows="4" required></textarea>

		<input type="submit" value="Submit">
	</form>
</div>
<!-- End Contact -->
{%endblock%}

<!-- <a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a> -->